### ISSUE TITLE
i simply can't get set's working at all.

### ISSUE THREAD

**Issue by jayenne** [driesvints/blade-icons#159]
hi, I have a problem getting sets working. I have installed it and working perfectly. I'm not using any icon packages, only my own svgs and select fontawesome as svgs only (not fa's js or css etc.).

my problems is when i give a 'set' prefix it fails with `Unable to locate a class or view for component [...]` error.
I am using the 1.0.2 release via npm, published the config, uncommented the default set, created a new set called 'appicons' (with a differnent default set of classes).

when i call them within blade `<x-icon name="light.bullhorn" class="..."/>` works, but `<x-appicon name="light.bullhorn" class="..."/>` fails.

the relevant config snippet is ...
```
'default' => [
    'paths' => [
        'resources/svg/app',
        'resources/svg/fa',
    ],
    'disk' => '',
    'prefix' => 'svg',
    'fallback' => '',
    'class' => 'set-default',
    'attributes' => [
    ],
],
'appicons' => [
    'paths' => [
        'resources/svg/app',
        'resources/svg/fa',
    ],
    'disk' => '',
    'prefix' => 'appicon',
    'fallback' => '',
    'class' => 'set-appicon',
    'attributes' => [
    ],
],
```

I'd love to understand better why this isn't working.
also - if you have any questions please ask.

**Comment by driesvints** [comment]
Hey jayenne. That's the expected behavior. `<x-appicon name="light.bullhorn" class="..."/>` syntax doesn't exists. I'm not sure where you read that?

Either one of these two will work in your case:

```blade
<x-icon name="light.bullhorn" class="..."/>
<x-light.bullhorn class="..."/>
```

Which will retrieve the `bullhorn.svg` icon in the `icons` directory in either the `resources/svg/app` or `resources/svg/fa` directory for the `default` set. If you want to look for `appicons` you'll need to do one of these:

```blade
<x-icon name="appicon-light.bullhorn" class="..."/>
<x-appicon-light.bullhorn class="..."/>
```

Closing this now but let me know if there's anything else not clear.

**Comment by jayenne** [comment]
I'm not sure where or how i thought that was the correct syntax but thank you for your examples. they are perfect :)
