### ISSUE TITLE
Question: How to provide fallback to @svg?

### ISSUE THREAD

**Issue by Luc45** [driesvints/blade-icons#23]
Hello,

How can I set a fallback to @svg if it can't find the specified icon?

This is what I did:

```
@php
  if (!file_exists(base_path(config('blade-svg.svg_path')).$item['icone'])) {
    $item['icone'] = 'icon-circle';
  }
@endphp
```

**Comment by adamwathan** [comment]
This isn't supported right now but I'd be open to a PR.

We could probably add a `default` method to the `Svg` class which you could then use like this:

```
<span>{{ svg_image('icon')->default('otherIcon') }}</span>
```

**Comment by Luc45** [comment]
Perhaps a convention over configuration philosophy could work fine in this case?

For example, instead of calling a default method, we could just pass a .png file with the same name as the .svg to make it less verbose.

If a fallback is necessary, it tries to load file.png instead of file.svg.

I can try to make a PR, yes :)

**Comment by adamwathan** [comment]
I don't like that idea; this is a library for dealing with SVG assets not PNGs.

When you say fallback do you mean fallback for browsers that don't support SVG? Originally you said "can't find the specified icon" so I assumed you had some use case where you would be trying to render SVGs that might not exist and needed to provide a default SVG.

I've personally never had that problem (I only render SVGs that I know exist; if it doesn't exist that's a bug in my code), so that's why the library doesn't currently support it. I don't mind providing the ability to handle what happens if an icon isn't found (although this probably won't work if someone is using spritesheets), but I don't have any intention of falling back to an `img` tag that references another asset type.

**Comment by meduzen** [comment]
Unless you target Android 2 or IE8-, SVG are available everywhere.

**Comment by akazorg** [comment]
Hello, great package @adamwathan. 

A fallback for browsers not supporting SVG would be a nice, even if it targets old browsers.

**Comment by adamwathan** [comment]
Closing this as no intent to support a fallback to non-SVG images.

**Comment by jayenne** [comment]
A fallback icon would be great, as with a config setting to fail gracefully on missing file error.
