### ISSUE TITLE
Why final?

### ISSUE THREAD

**Issue by jreviews** [driesvints/blade-icons#7]
Thanks for putting this together and sharing it. 

Just wondering why you decided to make the class final. I would like to use it outside of Laravel using Matt's approach for using Blade https://github.com/mattstauffer/Torch 

Alternatively, having getter methods for the list of icons would be useful.

**Comment by driesvints** [comment]
Heya @jreviews. Because I'd like to make changes if I need to to the internals without breaking people's apps. Final allows me to modify the non-public api of an object just like that. 

Btw, this package will be replaced by https://github.com/adamwathan/blade-svg/pull/50 soon. I think that iteration will allow you to make use of the package outside Laravel much easier. Although I'll need to maybe prevent the component registration in that case 🤔
