### ISSUE TITLE
Strip trailing slash from path

### ISSUE THREAD

**Issue by nathangross** [driesvints/blade-icons#79]
`@svg('icon-ui.checkmark-circle')` this works as expected, however `<x-icon-ui.checkmark-circle/>` does not. I'm sure I'm missing something really simple here 🤷🏻‍♂️

blade-icons.php

```
<?php

return [

    'sets' => [
        'default' => [
            'path' => 'resources/assets/svg/icons/',
            'prefix' => 'icon',
            'class' => '',
        ],
    ],
    'class' => '',
];
```

**Comment by driesvints** [comment]
I have a test right here which verifies the behavior: https://github.com/blade-ui-kit/blade-icons/blob/main/tests/ComponentsTest.php#L80-L94

Here's the view that's used: https://github.com/blade-ui-kit/blade-icons/blob/main/tests/resources/views/icon-subdirectory.blade.php

So there must be discrepancy here somewhere. Can you screenshot the directory structure of `resources/assets/svg/icons/`. Also: what happens when you remove the trailing slash from the `path` setting?

**Comment by driesvints** [comment]
FYI: you can omit the prefix for the "default" set when using the `@svg` directive or the `svg()` helper.

**Comment by nathangross** [comment]
Removing the tailing slash seems to have fixed my issue. Adding the dir structure (it's been updated since my previous message) screenshot anyway. 

<img width="1096" alt="Screen Shot 2020-08-21 at 2 42 33 PM" src="https://user-images.githubusercontent.com/380278/90923967-96b4a780-e3bc-11ea-8b79-0b369f0b4677.png">

Thanks for the reply and tip on removing the prefix on `@svg`!

**Comment by driesvints** [comment]
@nathangross glad you figured it out 👍 

I'm gonna re-open this issue to see if I can strip the trailing slash when an Icon set gets added so it doesn't matters if you set it or not.
